name: CI & Security Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # para 'checkout'
      security-events: write # para subir resultados de Snyk

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # O la versión que prefieras

    - name: Install dependencies and tools
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install snyk flake8

    - name: Lint with flake8
      run: |
        # Chequeo estricto de errores de sintaxis
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Chequeo más relajado de estilo (no falla el build)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Snyk to check dependencies (SCA)
      uses: snyk/actions/python@master
      env:
        # Debes guardar tu token en GitHub Secrets
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test --file=requirements.txt

    - name: Run Snyk to check code (SAST)
      uses: snyk/actions/code@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
